name: Build
on:
  workflow_call:
    inputs:
      artifact-name:
        description: the name of the deployable artifacts files # description of input information
        type: string # type of input information
        required: false # is this input required
        default: dist # default value
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifacts-name }}
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
